---
- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
- name: define gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: define repository docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: ensure docker is activated
  service:
    name: docker
    state: started
    enabled: yes

- name: restart docker
  service: 
    name: docker 
    state: restarted