- name: install
  package:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ fail2ban_dependencies }}"
  tags:
    - configuration
    - fail2ban
    - fail2ban-install