---
- name: create vm demo 
  become: false
  gather_facts: false

  pre_tasks:
    - include_vars: vars.yml

  tasks:
    - name: create folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter_name: "{{ vcenter_datacenter }}"
        folder_name: "{{ vcenter_destination_folder }}"
        folder_type: vm
        state: present


    - name: crete vm
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter_name: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
        folder: "{{ vcenter_destination_folder }}"
        state: "{{ vm_state }}"
        guest_id: "{{ vm_guestid }}"
        cluster: "{{ vcenter_cluster }}"
        disk:
          - size_gb: "{{ vm_disk_gb }}"
            type: "{{ vm_disk_type }}"
            datastore: "{{ vm_disk_datastore }}"
        hardware:
          memory_mb: "{{ vm_hw_ram_mb }}"
          num_cpus: "{{ vm_hw_cpu_n }}"
          scsi: "{{ vm_hw_scsi }}"
        network:
          - name: "{{ vm_net_name }}"
            device_name: "{{ vm_net_type }}"
