---

- name: Include vars
  include_vars:
    file: vars.yml

- name: ensure backup directory exists
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    mode: 0777
    owner: mongodb

- name: Create MongoDB backup using mongodb_shell module
  community.mongodb.mongodb_shell:
    login_database: "{{ login_database }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    database: "{{ db_name }}"
    collection: ""
    command: "db.copyTo('{{ backup_dir }}/{{ db_name }}.bson')"
    args:
      host: localhost
  become: yes
  become_user: mongodb

- name: Compress MongoDB backup
  ansible.builtin.command:
    cmd: "tar -czvf {{ backup_dir }}/{{ db_name }}.tar.gz {{ backup_dir }}/{{ db_name }}.bson"
  become: yes  

- name: Downloading backup file to localhost
  ansible.builtin.fetch:
    src: "{{ backup_dir }}/{{ db_name }}.tar.gz"
    dest: "{{ path }}/{{ db_name }}.tar.gz"
    flat: yes  
