---
- name: Include vars
  include_vars:
    file: vars.yml

- name: Upgrade system
  yum:
    name: '*'
    state: latest

- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: install letsencrypt
  yum:
    name: letsencrypt
    state: latest

- name: create letsencrypt directory
  file:
    path: /var/www/letsencrypt
    state: directory

- name: Remove default nginx config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Install system nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Install nginx site for letsencrypt requests
  template:
    src: templates/nginx-http.j2
    dest: /etc/nginx/conf.d/http.conf

- name: Reload nginx to activate letsencrypt site
  service:
    name: nginx
    state: restarted

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for specified site
  template:
    src: templates/nginx-le.j2
    dest: /etc/nginx/conf.d/le.conf

- name: Reload nginx to activate specified site
  service:
    name: nginx
    state: restarted

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: "{{ time }}"
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && service nginx reload
