---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup.yml
  when: ansible_os_family == 'Debian'

- include_tasks: freebsd.yml
  when: ansible_os_family == 'FreeBSD'

- include_tasks: openbsd.yml
  when: ansible_os_family == 'OpenBSD'

- include_tasks: setup-linux.yml
  when: ansible_os_family == 'Archlinux'

- import_tasks: virtualhost_conf.yml

- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx service is running as configured.
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
...      
